package snippets7;

/**
 * Created by root on 13/3/16.
 */
public class JavaStringSplitExample {
    public static void main(String[] args) {

        /**
         *Java String class defines following methods to split Java String object.
         *String[] split( String regularExpression )
         *Splits the string according to given regular expression.
         *String[] split( String reularExpression, int limit )
         *Splits the string according to given regular expression. The number of resultant
         *substrings by splitting the string is controlled by limit argument.
         */

        String str1="one-two-three";
        String delimiter1="-";
        String temp[];

        temp=str1.split(delimiter1);
        for (String s1:temp
             ) {
            System.out.println("s1 = " + s1);
        }


        String str2="one.two.three";
        String delimiter2="\\.";
        
        temp=str2.split(delimiter2);
        for (String s2:temp
             ) {
            System.out.println("s2 = " + s2);
        }
  /**
  *Using second argument in the String.split() method, we can control the maximum
  *number of substrings generated by splitting a string.
  */

        temp=str2.split("\\.",2);
        for (String s3:
             temp) {
            System.out.println("s3 = " + s3);
        }
    }
}
